### ISSUE TITLE
Training times

### ISSUE THREAD

**Issue by roodrallec** [tiberiu44/TTS-Cube#26]
Hello Tiberiu,
Thanks for making the code for TTS-Cube available, I'm finding it really useful for my thesis. 

However, I'm currently looking to train TTS-Cube on audio and transcripts extracted from interviews. What kind of training times were you seeing for 

A) training the G2P model; 
B) training the Vocoder; 
C) training the encoder.

Also, once trained is the synthesis fast enough for real-time TTS?

**Comment by tiberiu44** [comment]
Hi @roodrallec ,
Glad to hear you find this project useful. 

A) Currently, we don't use the G2P model in any way. I found it useful to rather rely on the encoder to learn phonetic transcriptions, because it reflects the distribution of words that are actually used in conversations. Training on CMU (or other lexicons), just adds noise, because the examples in this lexicons don't reflect the actual occurrences of words. Also, there are a lot of exceptions where the pronunciation of words (in terms of phonetics and accent) depends on context.
B) Training the vocoder takes about a month (2 weeks for Wavenet and another 2 weeks for ParallelWavenet)
C) Training the encoder took me three weeks.

I suggest you just start by training the encoder and use the pretrained models for Vocoding. They are multi-speaker and it is likely that you won't have to training anything else. Just one important thing: the models are at 24Khz, so it is required that your data is also sampled at least 24Khz. TTS-Cube will downsample them automatically if it needs to.

You can try, every now and then, to synthesize new samples using the pre-trained models and your vocoder. Just stop when you feel that the results are good enough. As an observation: the encoder model will stay a lot of time in a state where it generated muffled sounds. After a while, the results will improve a lot.

Yes, it is fast enough for real-time TTS, given that you have a GPU. I got good results (for faster then realtime synthesis runtime) on a GTX 1060.
