### ISSUE TITLE
Integration with LPCNET

### ISSUE THREAD

**Issue by alokprasad** [tiberiu44/TTS-Cube#28]
Any idea What needs to be done to replace vocoder from wavernn to lpcnet?

**Comment by tiberiu44** [comment]
Right now the vocoder is Clarinet, not wavernn. For LPC net you could just modify sybthesis.py to use the external vocoder instead of the internal one and also build an encoder that predicts LPC (probably just modify the corpus import function). Do you plan to do this? It would be great to have cpu synthesis.
