### ISSUE TITLE
what is the present inference for generating 10sec audio using vocoder?

### ISSUE THREAD

**Issue by saibharani** [tiberiu44/TTS-Cube#31]
I want to know the general inference time of generating 10sec audio using the vocoder presently i don't have the setup to test it on my own can anyone help
thank you

**Comment by tiberiu44** [comment]
Hi @saibharani ,

You can use this Notebook to run your tests: https://colab.research.google.com/drive/1cws1INmucRJ702eV4sKNJHzMDvrkg_lh

You don't need any local setup, just open the notebook in "playground mode". The code will display the inference time - it will actually take longer, because the code loads the models every time. It should take about 5 seconds on whatever Google Collaboratory uses and about 2.5 seconds on a GTX 1080.

**Comment by saibharani** [comment]
thanks for the immediate response i will check the above link and get back if needed.
thanks again
